spring:
  profiles:
    active: local
    
  application:
    name: splitmate-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/splitmate
    username: splitmate
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true